### ISSUE TITLE
Fix undefined variable notice

### ISSUE THREAD

**Issue by rnagle** [INN/super-cool-ad-inserter-plugin#17]
See:

    Notice: Undefined variable: i in /vagrant/wp-content/plugins/super-cool-ad-inserter-plugin/inc/scaip-shortcode-inserter.php on line 65
    Notice: Undefined variable: i in /vagrant/wp-content/plugins/super-cool-ad-inserter-plugin/inc/scaip-shortcode-inserter.php on line 68
    Notice: Undefined variable: i in /vagrant/wp-content/plugins/super-cool-ad-inserter-plugin/inc/scaip-shortcode-inserter.php on line 84

**Comment by aschweigert** [comment]
ok to close?
