### ISSUE TITLE
Should the shortcode inserter function's decision to filter be affected by an action or filter?

### ISSUE THREAD

**Issue by benlk** [INN/super-cool-ad-inserter-plugin#25]
Or should it always and only be controlled by the theme-wide options and by the per-post override in the post meta?

The affected function: https://github.com/INN/super-cool-ad-inserter-plugin/blob/master/inc/scaip-shortcode-inserter.php#L12

**Comment by aschweigert** [comment]
should probably be filterable

**Comment by aschweigert** [comment]
a couple example use-cases:

1) A site has a meta field for excluding all ads on a given post. This applies to both ads added in widgets or directly in templates as well as inline ad units that would be added by this plugin.
2) A site wants to use a different html tag (or set of tags) for counting the number of elements between ads, so maybe a site wants to insert an ad before/after every <h3> in a post, for example.
