### ISSUE TITLE
coding standards

### ISSUE THREAD

**Issue by aschweigert** [INN/super-cool-ad-inserter-plugin#31]
make sure plugin conforms to wp coding standards

**Comment by benlk** [comment]
Are we worried about the tests directory conforming?

**Comment by aschweigert** [comment]
any reason it wouldn't?

**Comment by benlk** [comment]
A lot of the boilerplate code is written without spaces in the braces: https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#brace-style

**Comment by aschweigert** [comment]
where did the boilerplate come from?

**Comment by benlk** [comment]
Largo, probably? We've been copying it form plugin to plugin.
