### ISSUE TITLE
Test against Wordpress 5.4 RC

### ISSUE THREAD

**Issue by benlk** [INN/super-cool-ad-inserter-plugin#51]

**Comment by joshdarby** [comment]
Testing against the 5.4 RC went well! Everything works as expected and no ugly errors, warnings or notices are displayed anywhere.

**Comment by benlk** [comment]
If it works, can you bump the tested-up-to string in the plugin readme, and get that update posted to wordpress.org?

**Comment by joshdarby** [comment]
@benlk Done. I _think_ it worked without updating the version number. Here's the commit in the SVN repo: https://plugins.trac.wordpress.org/changeset/2258413, but it's not showing on the plugin page yet https://wordpress.org/plugins/super-cool-ad-inserter/

Maybe it just needs to think for a few minutes 😬

**Comment by benlk** [comment]
I don't see the update yet on https://wordpress.org/plugins/super-cool-ad-inserter/ but will check back in a while.

**Comment by joshdarby** [comment]
@benlk I still don't see the update on the plugin page 😖 I think we may need to bump the version number.

**Comment by joshdarby** [comment]
@benlk Do you think it's worth doing an entire release and having people update the plugin just to bump up the "Tested" WP number?

**Comment by benlk** [comment]
I'd email plugins@wordpress.org with the commit link and ask them what's up, before doing the full release.

**Comment by joshdarby** [comment]
Response from WP:

```
https://plugins.svn.wordpress.org/super-cool-ad-inserter/trunk/readme.txt has an INVALID version of WordPress.

Make it 5.4, not 5.4-beta -- our system ignores the latter.

https://plugins.svn.wordpress.org/super-cool-ad-inserter/tags/0.2/readme.txt too.
```

So I guess I'll try updating it to `5.4` and pushing it again.

**Comment by joshdarby** [comment]
I updated it to `5.4` yesterday afternoon and pushed it to the WP repo, but it still isn't displaying the updated number in the WP directory 😕

Here's the SVN commit: https://plugins.trac.wordpress.org/changeset/2259344

**Comment by benlk** [comment]
Then I guess we need to bump the version number, to fix the problem with tagged version 0.2 not having the right metadata.

`0.2.1` time?

**Comment by joshdarby** [comment]
@benlk `0.2.1` is now released and shows the correct "Tested up to" number finally https://wordpress.org/plugins/super-cool-ad-inserter/

SVN commit: https://plugins.trac.wordpress.org/changeset/2260566

**Comment by benlk** [comment]
Hooray!

Thank you for getting this fixed!
