### ISSUE TITLE
Plugin deactivation scripts:

### ISSUE THREAD

**Issue by benlk** [INN/super-cool-ad-inserter-plugin#7]
- What happens when the plugin is deactivated?
- If #2 saves the shortcode to the post, should the deactivation script remove the shortcodes?

**Comment by aschweigert** [comment]
how critical is this?

**Comment by benlk** [comment]
Not at all critical. It's definitely something we should consider, though.

**Comment by aschweigert** [comment]
scrubbing shortcodes wouldn't be a bad idea...but since they're not inserted by default and that feature is very poorly documented...meh?

**Comment by benlk** [comment]
meh, agreed. #2 doesn't save the shortcode to the post.
